- name: Install required packages
  ansible.builtin.apt:
    name:
      - nfs-common  # Required for mounting NFS volumes in Kubernetes
    state: present
    update_cache: yes

- name: Adjust kernel parameters
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - {name: "fs.inotify.max_queued_events", value: 16384}
    - {name: "fs.inotify.max_user_instances", value: 8192}
    - {name: "fs.inotify.max_user_watches", value: 524288}
