staticPersistence:
  enabled: true
  nfsServer: 192.168.20.92
  dataVolume:
    path: /volume4/data
    size: 3Ti

app-template:
  defaultPodOptions:
    securityContext:
      runAsUser: 1029
      runAsGroup: 100
      fsGroup: 100
  controllers:
    main:
      containers:
        main:
          image:
            repository: docker.io/jellyfin/jellyfin
            tag: 10.8.13
        prowlarr:
          image:
            repository: lscr.io/linuxserver/prowlarr
            tag: 1.13.3
        radarr:
          image:
            repository: lscr.io/linuxserver/radarr
            tag: 5.3.6
        sonarr:
          image:
            repository: lscr.io/linuxserver/sonarr
            tag: 4.0.2
        jellyseerr:
          image:
            repository: docker.io/fallenbagel/jellyseerr
            tag: 1.7.0
        bazarr:
          image:
            repository: lscr.io/linuxserver/bazarr
            tag: latest
        lidarr:
          image:
            repository: lscr.io/linuxserver/lidarr
            tag: latest
  service:
    main:
      ports:
        http:
          port: 8096
          protocol: HTTP
        transmission:
          port: 9091
          protocol: HTTP
        prowlarr:
          port: 9696
          protocol: HTTP
        radarr:
          port: 7878
          protocol: HTTP
        sonarr:
          port: 8989
          protocol: HTTP
        jellyseerr:
          port: 5055
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &jellyfinHost jellyfin.achapelin.com
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
        - host: &prowlarrHost prowlarr.achapelin.com
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: prowlarr
        - host: &radarrHost radarr.achapelin.com
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: radarr
        - host: &sonarrHost sonarr.achapelin.com
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: sonarr
        - host: &jellyseerrHost jellyseerr.achapelin.com
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: jellyseerr
        - host: &bazarrHost bazarr.achapelin.com
          paths:
            - path: /
              pathType: Prefix
              service:
                name: jellyfin-bazarr
                port: 6767
        - host: &lidarrHost lidarr.achapelin.com
          paths:
            - path: /
              pathType: Prefix
              service:
                name: jellyfin-lidarr
                port: 8686
      tls:
        - secretName: jellyfin-tls-certificate
          hosts:
            - *jellyfinHost
            - *prowlarrHost
            - *radarrHost
            - *sonarrHost
            - *jellyseerrHost
            - *bazarrHost
            - *lidarrHost
  persistence:
    # NFS data volume for media content
    data:
      enabled: true
      existingClaim: jellyfin-data-pvc
      advancedMounts:
        main:
          main:
            - path: /data/media
              subPath: media
          radarr:
            - path: /data
          sonarr:
            - path: /data
          bazarr:
            - path: /data/media
              subPath: media
          lidarr:
            - path: /data/media
              subPath: media

    # Config storage on default storage class (Rook-CEPH)
    config:
      enabled: true
      accessMode: ReadWriteOnce
      size: 50Gi
      advancedMounts:
        main:
          main:
            - path: /config
              subPath: jellyfin/config
          prowlarr:
            - path: /config
              subPath: prowlarr/config
          radarr:
            - path: /config
              subPath: radarr/config
          sonarr:
            - path: /config
              subPath: sonarr/config
          jellyseerr:
            - path: /app/config
              subPath: jellyseerr/config
          lidarr:
            - path: /config
              subPath: lidarr/config
          bazarr:
            - path: /config
              subPath: bazarr/config
